"""The reference bundle is the unit an auditor is handed: runtime-reference.jsonl
+ quality-reference.jsonl + fiches/ + roster/models.json + suite-definitions/.
Every row's pointers must resolve inside that bundle -- this is the current-
schema bundle only, named explicitly, never a glob over every `*-reference*.jsonl`
(which would silently pull in the superseded `*.schema-1.jsonl` files).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from wave_local_ai_v2 import (
    bundle_merge,
    fiche_registry,
    machines,
    profiles,
    read_model,
    results,
    roster,
    row_contract,
    settings,
    suite_snapshot,
)
from wave_local_ai_v2.read_model import (
    ABSENT_POINTER_UNRESOLVED,
    ABSENT_PREDATES_SCHEMA,
    Absent,
)

RESULTS_DIR = Path("aidd_docs/results")
# Read from settings rather than rebuilt here, like the fiche and roster
# pointers this file already resolves that way.
RUNTIME_REFERENCE_PATH = Path(settings.DEFAULT_RUNTIME_REFERENCE_PATH)
QUALITY_REFERENCE_PATH = Path(settings.DEFAULT_QUALITY_REFERENCE_PATH)
SUITE_DEFINITIONS_DIR = Path(settings.DEFAULT_SUITE_DEFINITIONS_DIR)
REFUSALS_REFERENCE_PATH = Path(settings.DEFAULT_REFUSALS_REFERENCE_PATH)
SUPERSEDED_PATHS = (
    RESULTS_DIR / "runtime-reference.schema-1.jsonl",
    RESULTS_DIR / "quality-reference.schema-1.jsonl",
    RESULTS_DIR / "runtime-reference.schema-7.jsonl",
    RESULTS_DIR / "quality-reference.schema-7.jsonl",
)
# The schema the published bundle was produced under, stated here rather than
# read from `row_contract.SCHEMA_VERSION`. Asserting against the live constant
# would make every schema bump fail this test until the bundle matched it
# again, and the cheapest way to make it match is to hand-edit published rows
# -- exactly what `aidd_docs/results/README.md` forbids ("a hand-edited row is
# no longer the row the harness wrote"). Pinning the version instead keeps the
# bundle internally uniform and makes the lag explicit: this constant moves
# only when the bundle is regenerated by real runs, per Story 19's protocol.
PUBLISHED_BUNDLE_SCHEMA_VERSION = "30"


def _all_rows() -> list[dict[str, object]]:
    return results.read_rows(RUNTIME_REFERENCE_PATH) + results.read_rows(
        QUALITY_REFERENCE_PATH
    )


def test_every_row_resolves_its_fiche_hash() -> None:
    fiche_registry_dir = settings.DEFAULT_FICHE_REGISTRY_DIR
    for row in _all_rows():
        fiche_hash = row["fiche_hash"]
        assert isinstance(fiche_hash, str)
        assert (
            fiche_registry.read_fiche(fiche_hash, Path(fiche_registry_dir)) is not None
        ), f"row {row['run_id']!r} cites unresolved fiche_hash {fiche_hash!r}"


def test_every_cited_fiche_still_hashes_to_its_own_name() -> None:
    # Existence is not integrity: a hand-edited fiche still resolves, but it
    # is no longer the fiche the harness wrote.
    fiche_registry_dir = Path(settings.DEFAULT_FICHE_REGISTRY_DIR)
    # Each fiche is verified under the projection its citing row's own
    # schema_version selects, never under whatever the code writes today.
    cited = {(str(row["fiche_hash"]), row["schema_version"]) for row in _all_rows()}
    for fiche_hash, schema_version in sorted(cited, key=str):
        verification = fiche_registry.verify_fiche(
            fiche_hash, fiche_registry_dir, schema_version=schema_version
        )
        assert verification["status"] == "ok", (
            f"fiche {fiche_hash!r} is {verification['status']!r}: "
            f"{verification['changed_fields']}"
        )


def test_every_row_resolves_its_roster_entry_id() -> None:
    loaded_roster = roster.load_roster(Path(settings.DEFAULT_ROSTER_PATH))
    for row in _all_rows():
        roster_entry_id = row["roster_entry_id"]
        assert roster_entry_id in loaded_roster.entries, (
            f"row {row['run_id']!r} cites unresolved roster_entry_id "
            f"{roster_entry_id!r}"
        )


def test_every_quality_row_resolves_its_suite_definition() -> None:
    quality_rows = results.read_rows(QUALITY_REFERENCE_PATH)
    for row in quality_rows:
        suite_id = row["suite_id"]
        suite_version = row["suite_version"]
        # Resolved by the pair the row cites, not by the id alone: a bumped
        # suite adds a definition file beside its predecessor, so a published
        # row keeps resolving to the definition it was actually produced
        # against rather than to whatever now wears its suite's name.
        snapshot_path = SUITE_DEFINITIONS_DIR / suite_snapshot.snapshot_filename(
            suite_id, suite_version
        )
        assert snapshot_path.exists(), (
            f"row {row['run_id']!r} cites unresolved suite "
            f"{suite_id!r}@{suite_version!r}"
        )
        snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
        assert snapshot["suite_id"] == suite_id
        assert snapshot["suite_version"] == row["suite_version"]
        # The hash, not the version, is what catches a suite edited without a
        # version bump -- the one drift `suite_version` alone cannot see.
        assert snapshot["prompt_set_hash"] == row["prompt_set_hash"]


def _rows_owing_a_machine() -> list[tuple[row_contract.RowKind, dict[str, object]]]:
    """Every bundle row whose schema owes `machine_id` (from "23"), by kind.

    A row below it predates the field and claims no machine; a row at or
    above it that lacks the key reads as `None` and fails to resolve.
    """
    floor = int(row_contract.MACHINE_FICHE_SCHEMA_VERSION)
    kinded: list[tuple[row_contract.RowKind, dict[str, object]]] = [
        ("runtime", row) for row in results.read_rows(RUNTIME_REFERENCE_PATH)
    ] + [("quality", row) for row in results.read_rows(QUALITY_REFERENCE_PATH)]
    return [
        (kind, row) for kind, row in kinded if int(str(row["schema_version"])) >= floor
    ]


def test_every_rows_machine_id_resolves_to_a_declared_entry() -> None:
    assert (
        bundle_merge.unresolved_machine_rows(
            _rows_owing_a_machine(), machines.declared_machine_ids()
        )
        == []
    )


def test_no_two_machines_rows_share_a_fiche_hash() -> None:
    rows = [row for _kind, row in _rows_owing_a_machine()]
    collisions = bundle_merge.fiche_collisions(rows, machines.declared_machine_ids())
    assert [c.describe() for c in collisions] == []


def test_every_refusal_record_resolves_its_roster_entry_machine_and_profile() -> None:
    records = results.read_rows(REFUSALS_REFERENCE_PATH)
    loaded_roster = roster.load_roster(Path(settings.DEFAULT_ROSTER_PATH))
    assert (
        bundle_merge.unresolved_refusals(
            records,
            roster_entry_ids=loaded_roster.entries,
            profile_registry=profiles.tracked_registry(),
            declared=machines.declared_machine_ids(),
        )
        == []
    )


def test_the_three_bundle_assertions_refuse_a_constructed_violation() -> None:
    # The republished bundle holds one machine and no refusal, so the three
    # above cannot meet a collision or a stray machine there; this proves
    # each one bites.
    declared = machines.declared_machine_ids()
    laptop = {"machine_id": "laptop-mobile-gpu", "fiche_hash": "h", "run_id": "a"}
    tower = {"machine_id": "tower-desktop-gpu", "fiche_hash": "h", "run_id": "b"}
    stray = {"machine_id": "garage-box", "fiche_hash": "g", "run_id": "c"}
    assert bundle_merge.unresolved_machine_rows([("runtime", stray)], declared)
    assert bundle_merge.fiche_collisions([laptop, tower], declared)
    refusal = {
        "roster_entry_id": "ghost",
        "machine_id": "garage-box",
        "profile_id": "ghost@garage-box/gpu",
    }
    assert (
        len(
            bundle_merge.unresolved_refusals(
                [refusal],
                roster_entry_ids=[],
                profile_registry=profiles.tracked_registry(),
                declared=declared,
            )
        )
        == 3
    )


def test_a_runtime_verdict_never_crosses_a_model_or_a_compute_mode() -> None:
    # Each second run is decided against its own first: the same roster entry
    # in the same mode. A gpu run is never a reproduction of a cpu_only one.
    rows = {row["run_id"]: row for row in results.read_rows(RUNTIME_REFERENCE_PATH)}
    decided = 0
    for row in rows.values():
        verdict = row["verdict"]
        assert isinstance(verdict, dict)
        reference_run_id = verdict["reference_run_id"]
        if reference_run_id is None:
            continue
        reference = rows[str(reference_run_id)]
        assert (reference["roster_entry_id"], reference["compute_mode"]) == (
            row["roster_entry_id"],
            row["compute_mode"],
        )
        assert verdict["verdict"] in ("reproduced", "not_reproduced")
        decided += 1
    assert decided == len(rows) // 2


def test_a_cpu_only_row_reads_vram_as_not_applicable_everywhere() -> None:
    cpu_only = [
        row
        for row in results.read_rows(RUNTIME_REFERENCE_PATH)
        if row["compute_mode"] == "cpu_only"
    ]
    assert cpu_only
    for row in cpu_only:
        repetitions = row["repetitions"] + row["warmup_repetitions"]
        assert isinstance(repetitions, list)
        assert {row["vram_used_mib"]} | {
            repetition["vram_used_mib"] for repetition in repetitions
        } == {row_contract.VRAM_NOT_APPLICABLE}


def test_every_row_carries_the_published_bundle_schema_version() -> None:
    for row in _all_rows():
        assert row["schema_version"] == PUBLISHED_BUNDLE_SCHEMA_VERSION


def test_the_published_bundle_schema_version_is_not_ahead_of_the_code() -> None:
    # A bundle claiming a version the code cannot write would mean the rows
    # were edited rather than produced. Behind is allowed (a bump lands before
    # the regeneration that follows it); ahead never is.
    # Compared as integers: "10" sorts before "7" as a string.
    assert int(PUBLISHED_BUNDLE_SCHEMA_VERSION) <= int(row_contract.SCHEMA_VERSION)


def test_superseded_files_exist_and_are_not_the_published_schema() -> None:
    for path in SUPERSEDED_PATHS:
        assert path.exists(), f"expected superseded file at {path}"
        for row in results.read_rows(path):
            schema_version = row.get("schema_version")
            if schema_version is not None:
                assert schema_version != PUBLISHED_BUNDLE_SCHEMA_VERSION


# --------------------------------------------------------------------------
# The same read path a reader will actually use, over the published bundle.
#
# Republished on 2026-10-04 under schema "30", the code's own: the fields the
# schema-"7" bundle predated now come back as the row's values. The declared
# absence a row below a field's schema reads as is asserted over the
# superseded schema-7 rows in tests/test_read_model.py.
# --------------------------------------------------------------------------

FICHE_REGISTRY_DIR = Path(settings.DEFAULT_FICHE_REGISTRY_DIR)
ROSTER_PATH = Path(settings.DEFAULT_ROSTER_PATH)
# Named fields the schema-"7" bundle predated, asserted by name: `retries`/
# `resumed` arrived at "8", `thinking_policy` at "11". The whole judge block
# is conditional and no CLI that produced this bundle ever wrote it.
FIELDS_THE_SCHEMA_7_BUNDLE_PREDATED = ("thinking_policy", "retries", "resumed")


def _bundle_roster() -> roster.RosterFile | None:
    return read_model.load_roster_file(ROSTER_PATH)


def _bundle_runtime_view() -> dict[str, object]:
    run_id = results.read_rows(RUNTIME_REFERENCE_PATH)[0]["run_id"]
    view = read_model.runtime_view(
        RUNTIME_REFERENCE_PATH,
        str(run_id),
        PUBLISHED_BUNDLE_SCHEMA_VERSION,
        FICHE_REGISTRY_DIR,
        _bundle_roster(),
        read_model.load_machine_registry(Path(machines.DEFAULT_REGISTRY_PATH)),
    )
    assert view is not None
    return view


def _bundle_quality_view() -> dict[str, object]:
    run_id = results.read_rows(QUALITY_REFERENCE_PATH)[0]["run_id"]
    view = read_model.quality_view(
        QUALITY_REFERENCE_PATH,
        str(run_id),
        PUBLISHED_BUNDLE_SCHEMA_VERSION,
        _bundle_roster(),
        SUITE_DEFINITIONS_DIR,
        FICHE_REGISTRY_DIR,
    )
    assert view is not None
    return view


def _bundle_energy_view(path: Path, store: str) -> dict[str, object]:
    run_id = results.read_rows(path)[0]["run_id"]
    view = read_model.energy_view(
        path, str(run_id), PUBLISHED_BUNDLE_SCHEMA_VERSION, store
    )
    assert view is not None
    return view


def _walk(value: object) -> list[object]:
    found = [value]
    if isinstance(value, dict):
        for item in value.values():
            found += _walk(item)
    elif isinstance(value, list):
        for item in value:
            found += _walk(item)
    return found


def _all_bundle_views() -> list[dict[str, object]]:
    return [
        read_model.runs_view(
            RUNTIME_REFERENCE_PATH,
            QUALITY_REFERENCE_PATH,
            PUBLISHED_BUNDLE_SCHEMA_VERSION,
            _bundle_roster(),
        ),
        _bundle_runtime_view(),
        _bundle_quality_view(),
        _bundle_energy_view(RUNTIME_REFERENCE_PATH, "runtime"),
        _bundle_energy_view(QUALITY_REFERENCE_PATH, "quality"),
    ]


def test_all_four_views_answer_over_the_committed_bundle() -> None:
    views = _all_bundle_views()

    assert all(view for view in views)
    for view in views[1:]:
        assert view["schema_floor"] == PUBLISHED_BUNDLE_SCHEMA_VERSION
        assert view["unreadable"] == []
        assert view["entries"]


@pytest.mark.parametrize("field", FIELDS_THE_SCHEMA_7_BUNDLE_PREDATED)
def test_a_field_the_schema_7_bundle_predated_is_now_the_rows_value(
    field: str,
) -> None:
    entry = _bundle_quality_view()["entries"][0]  # type: ignore[index]
    (row,) = [
        row
        for row in results.read_rows(QUALITY_REFERENCE_PATH)
        if (row["run_id"], row["provider"], row["item_id"])
        == (entry["run_id"], entry["provider"], entry["item_id"])
    ]

    assert not isinstance(entry[field], Absent)
    assert entry[field] == row[field]


def test_the_whole_judge_block_is_absent_naming_the_bundles_version() -> None:
    judge = _bundle_quality_view()["entries"][0]["judge"]  # type: ignore[index]

    assert set(judge) == set(row_contract.JUDGED_FIELDS)
    for name, value in judge.items():
        assert value == Absent(
            ABSENT_PREDATES_SCHEMA,
            {"row_schema_version": PUBLISHED_BUNDLE_SCHEMA_VERSION},
        ), f"{name} is not a declared absence: {value!r}"


def test_no_bundle_row_yields_an_unresolved_pointer_in_any_view() -> None:
    # The bundle's five-part completeness, already asserted field by field
    # above, asserted again through the read path a reader will actually use.
    unresolved = [
        node
        for view in _all_bundle_views()
        for node in _walk(view)
        if isinstance(node, Absent) and node.reason == ABSENT_POINTER_UNRESOLVED
    ]

    assert unresolved == []


def test_every_row_of_a_superseded_file_lands_in_unreadable() -> None:
    for path in SUPERSEDED_PATHS:
        read = results.read_rows_from_floor(path, PUBLISHED_BUNDLE_SCHEMA_VERSION)

        assert read.rows == [], f"{path} rendered a row at floor 7"
        assert sum(entry.count for entry in read.unreadable) == len(
            results.read_rows(path)
        )


def test_the_publication_batch_has_a_development_pair_on_the_same_subject() -> None:
    """Every published classification batch over a publication suite stands
    beside a development-level batch of the hand-written classification suite
    with the same roster entry, fiche, engine build and commit. Rows carry no
    session id, so that key is the pair's definition, checkable from the rows
    alone; the commit is in it so that an earlier batch of the same subject on
    the same fiche never stands in for the one run beside it."""
    batches: dict[str, dict[str, object]] = {}
    for row in results.read_rows(QUALITY_REFERENCE_PATH):
        batches.setdefault(str(row["run_id"]), row)
    publication = [
        row
        for row in batches.values()
        if row["suite_level"] == "publication" and row["task_suite"] == "classification"
    ]

    def pair_key(row: dict[str, object]) -> tuple[object, ...]:
        return (
            row["roster_entry_id"],
            row["fiche_hash"],
            row["engine_build"],
            row["commit_sha"],
        )

    development = {
        pair_key(row)
        for row in batches.values()
        if row["suite_id"] == "classification-support-routing"
        and row["suite_level"] == "development"
        and row["score_interval"] is not None
    }
    assert publication
    for row in publication:
        assert row["score_interval"] is not None
        assert pair_key(row) in development, pair_key(row)
